Repository dotnet/orleans, pull requests merged in 2022-02, with the labels that each got.

#7551 Streaming: make PubSubStore configurable per provider
  src/Orleans.Core.Abstractions/Providers/ProviderConstants.cs
  src/Orleans.Streaming.Abstractions/StreamId.cs
  src/Orleans.Streaming/Hosting/SiloBuilderStreamingExtensions.cs
  src/Orleans.Streaming/InternalStreamId.cs
  src/Orleans.Streaming/PubSub/PubSubRendezvousGrain.cs
  src/Orleans.Streaming/SiloPersistentStreamConfigurator.cs
  test/Tester/StreamingTests/MemoryProgrammaticSubcribeTests.cs
  test/TesterInternal/StreamingTests/PubSubRendezvousGrainTests.cs
Labels: area-streaming

#7568 In CachedGrainLocator.Unregister, remove from cache using the address
  src/Orleans.Runtime/GrainDirectory/CachedGrainLocator.cs
Labels: Needs: backport

#7519 Fix vote counting bug where clock skew can incorrectly cause crashes in unstable clusters
  src/Orleans.Core/SystemTargetInterfaces/IMembershipTable.cs
  src/Orleans.Runtime/MembershipService/ClusterHealthMonitor.cs
  src/Orleans.Runtime/MembershipService/MembershipTableManager.cs
  test/NonSilo.Tests/Membership/MembershipTableManagerTests.cs
Labels: Needs: backport

#7611 Initial yaml pipeline for PR build/tests
  .azure/pipelines/pr.yaml
Labels: area-build
