Repository dotnet/orleans, pull requests merged in 2024-05, with the labels that each got.

#8982 Ensure reminder table is initialized before access
  src/Azure/Orleans.Reminders.AzureStorage/Storage/AzureBasedReminderTable.cs
  src/Azure/Orleans.Reminders.AzureStorage/Storage/RemindersTableManager.cs
  src/Orleans.Reminders/ReminderService/LocalReminderService.cs
  src/Orleans.Reminders/SystemTargetInterfaces/IReminderTable.cs
  test/Extensions/Tester.Cosmos/ReminderTests_Cosmos_Standalone.cs
  test/Extensions/TesterAzureUtils/Reminder/ReminderTests_Azure_Standalone.cs
  test/TesterInternal/RemindersTest/ReminderTableTestsBase.cs
Labels: Needs: backport

#9022 Mark Orleans.Streaming.AdoNet as alpha
  src/AdoNet/Orleans.Streaming.AdoNet/Orleans.Streaming.AdoNet.csproj
Labels: area-streaming

#9027 Use Entra ID auth in Azure tests when possible
  test/Extensions/ServiceBus.Tests/EventHubConfigurationExtensions.cs
  test/Extensions/ServiceBus.Tests/ServiceBus.Tests.csproj
  test/Extensions/ServiceBus.Tests/Streaming/EHBatchedSubscriptionMultiplicityTests.cs
  test/Extensions/ServiceBus.Tests/Streaming/EHClientStreamTests.cs
  test/Extensions/ServiceBus.Tests/Streaming/EHImplicitSubscriptionStreamRecoveryTests.cs
  test/Extensions/ServiceBus.Tests/Streaming/EHProgrammaticSubscribeTests.cs
  test/Extensions/ServiceBus.Tests/Streaming/EHStreamBatchingTests.cs
  test/Extensions/ServiceBus.Tests/Streaming/EHStreamCacheMissTests.cs
  test/Extensions/ServiceBus.Tests/Streaming/EHStreamPerPartitionTests.cs
  test/Extensions/ServiceBus.Tests/Streaming/EHStreamProviderCheckpointTests.cs
  test/Extensions/ServiceBus.Tests/Streaming/EHStreamingResumeTests.cs
  test/Extensions/ServiceBus.Tests/Streaming/EHSubscriptionMultiplicityTests.cs
  test/Extensions/ServiceBus.Tests/Streaming/EHSubscriptionObserverWithImplicitSubscribingTests.cs
  test/Extensions/ServiceBus.Tests/TestStreamProviders/TestAzureTableStorageStreamFailureHandler.cs
  test/Extensions/TesterAzureUtils/AzureMembershipTableTests.cs
  test/Extensions/TesterAzureUtils/AzureRemindersTableTests.cs
  test/Extensions/TesterAzureUtils/AzureStorageOperationOptionsExtensions.cs
  test/Extensions/TesterAzureUtils/GrainDirectory/AzureMultipleGrainDirectoriesTests.cs
  test/Extensions/TesterAzureUtils/Streaming/AQClientStreamTests.cs
  test/Extensions/TesterAzureUtils/Streaming/AQProgrammaticSubscribeTest.cs
  test/Extensions/TesterAzureUtils/Streaming/AQStreamFilteringTests.cs
  test/Extensions/TesterAzureUtils/Streaming/AQStreamingTests.cs
  test/Extensions/TesterAzureUtils/Streaming/AQStreamsBatchingTests.cs
  test/Extensions/TesterAzureUtils/Streaming/AQSubscriptionMultiplicityTests.cs
  test/Extensions/TesterAzureUtils/Streaming/AQSubscriptionObserverWithImplicitSubscribingTests.cs
  test/Extensions/TesterAzureUtils/Streaming/AzureQueueAdapterTests.cs
  test/Extensions/TesterAzureUtils/Streaming/DelayedQueueRebalancingTests.cs
  test/Extensions/TesterAzureUtils/Streaming/HaloStreamSubscribeTests.cs
  test/Extensions/TesterAzureUtils/Streaming/PullingAgentManagementTests.cs
  test/Extensions/TesterAzureUtils/Streaming/SampleAzureQueueStreamingTests.cs
  test/Extensions/TesterAzureUtils/Streaming/StreamReliabilityTests.cs
  test/TestInfrastructure/TestExtensions/TestUtils.cs
  test/Tester/Forwarding/ShutdownSiloTests.cs
  test/Tester/Tester.csproj
  test/TesterInternal/GeoClusterTests/BasicLogTestGrainTests.cs
  test/TesterInternal/TesterInternal.csproj
  test/Transactions/Orleans.Transactions.Azure.Test/AzureTransactionalStateStorageTests.cs
  test/Transactions/Orleans.Transactions.Azure.Test/Orleans.Transactions.Azure.Test.csproj
  test/Transactions/Orleans.Transactions.Azure.Test/TestFixture.cs
  test/Transactions/Orleans.Transactions.Azure.Test/TransactionRecoveryTests.cs
Labels: area-testing

#9029 Update Microsoft.Build dependency
  Directory.Packages.props
  test/Extensions/TesterAdoNet/Tester.AdoNet.csproj
Labels: area-build
